# Generated by Django 5.0.6 on 2024-08-06 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_conditions_profile_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='conditions',
        ),
        migrations.AddField(
            model_name='profile',
            name='allergies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='diseases',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
